# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adam Davies
masthead_title: ""
title_separator: "|"
email: adavies4@illinois.edu
description: "Adam Davies, CS PhD student @ UIUC."
twitter_username: adamdaviesnlp
# github_username: ahdavies6
linkedin_username: adamhdavies
minimal_mistakes_skin: dark
# search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# load github data 
github: [metadata]

include:
  - _pages

# # Exclude from processing.
# # The following items will not be processed, by default. Create a custom list
# # to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - minimal-mistakes-jekyll

author:
  name      : "Adam Davies"
  pronouns  : "he/they"
  avatar    : "/assets/images/me.jpg"
  bio       : "PhD candidate @ UIUC<br><small>NLP, interpretability, cognitive science</small>"
  uri       : "https://ahdavies6.github.io/"
  email     : adavies4@illinois.edu
  linkedin  : adamhdavies
  # location  : "Urbana, IL"
  twitter   : adamdaviesnlp
  # github    : ahdavies6
  links :
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/adamdaviesnlp.bsky.social"
    - label : "Scholar"
      icon  : "ai ai-google-scholar"
      url   : "https://scholar.google.com/citations?user=vqkOH7gAAAAJ&hl=en"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "/assets/docs/2025_Summer_CV.pdf"
    # - label: "ORCID"
    #   icon: "ai ai-orcid"
    #   url: "https://orcid.org/0000-0002-0610-2732"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/ahdavies6"
#     - label: "LinkedIn"
#       icon: "fab fa-fw fa-linkedin"
#       url: "https://www.linkedin.com/in/adamhdavies/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
